# kind: Namespace
# apiVersion: v1
# metadata:
#  name: expense
#  labels:
#   project: expense
#   environment: dev

kind: namespace
apiVersion: v1
metadata: 
     name: expense
     labels:
        project: expense
        env: dev